pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/abhishekgowdrum/devops-project4.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Create EC2') {
            steps {
                dir('Terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Get EC2 IP') {
            steps {
                script {
                    env.EC2_IP = sh(
                        script: 'cd terraform && terraform output -raw ec2_public_ip',
                        returnStdout: true
                    ).trim()

                    echo "EC2 Public IP: ${env.EC2_IP}"
                }
            }
        }

        stage('Create Ansible Inventory') {
            steps {
                sh """
                cat > ansible/inventory.ini <<EOF
[webserver]
app ansible_host=${EC2_IP} ansible_user=ec2-user ansible_ssh_private_key_file=/path/to/devops.pem
EOF
                """
            }
        }

        stage('Test Ansible Connection') {
            steps {
                sh '''
                ansible -i ansible/inventory.ini webserver -m ping
                '''
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                ansible-playbook \
                -i ansible/inventory.ini \
                ansible/deploy.yml
                '''
            }
        }
    }
}
