pipeline {

    agent any

     environment {
        DOCKER_USER = 'abhishekgowdrum'
        IMAGE_NAME  = 'devops-project2'
        IMAGE_TAG   = "${env.BUILD_NUMBER}"
        REGISTRY    = "${DOCKER_USER}/${IMAGE_NAME}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies & Test') {
            steps {
                sh '''
                    pip3 install -r requirements.txt
                    python3 -m pytest
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${REGISTRY}:${IMAGE_TAG} -t ${REGISTRY}:latest ."
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                        echo "\$PASS" | docker login -u "\$USER" --password-stdin
                        docker push ${REGISTRY}:${IMAGE_TAG}
                        docker push ${REGISTRY}:latest
                        docker logout
                    """
                }
            }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/abhishekgowdrum/devops-project4.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Create EC2') {
            steps {
                dir('Terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Get EC2 IP') {
            steps {
                script {
                    env.EC2_IP = sh(
                        script: 'cd Terraform && terraform output -raw ec2_public_ip',
                        returnStdout: true
                    ).trim()

                    echo "EC2 Public IP: ${env.EC2_IP}"
                }
            }
        }

        stage('Create Ansible Inventory') {
    steps {
        script {
            def ec2IP = sh(
                script: 'cd Terraform && terraform output -raw ec2_public_ip',
                returnStdout: true
            ).trim()

            sh """
                mkdir -p ansible

                cat > ansible/inventory.ini <<EOF
[webserver]
${ec2IP}

[webserver:vars]
ansible_user=ubuntu
ansible_private_key_file=/var/lib/jenkins/.ssh/west2.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOF
            """

            echo "Generated Ansible inventory:"
            sh 'cat ansible/inventory.ini'
        }
    }
}

        stage('Test Ansible Connection') {
            steps {
                sh '''
                ansible -i ansible/inventory.ini webserver -m ping
                '''
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                ansible-playbook \
                -i ansible/inventory.ini \
                ansible/playbook.yml
                '''
            }
        }
    }
}
