pipeline {

    agent any

     environment {
        DOCKER_USER = 'abhishekgowdrum'
        IMAGE_NAME  = 'devops-project2'
        IMAGE_TAG   = "${env.BUILD_NUMBER}"
        REGISTRY    = "${DOCKER_USER}/${IMAGE_NAME}"
    }

    stages {
         stage('Git') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/abhishekgowdrum/devops-project4.git'
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
stage('Checkout Application') {
    steps {
        dir('app') {
            git branch: 'main',
                url: 'https://github.com/abhishekgowdrum/devops-project2.git'
        }
    }
}

stage('Install Dependencies & Test') {
    steps {
        dir('app') {
            sh '''
                python3 -m venv venv
                ./venv/bin/python -m pip install --upgrade pip
                ./venv/bin/python -m pip install -r requirements.txt
                ./venv/bin/python -m pytest
            '''
        }
    }
}



stage('Build Docker Image') {
    steps {
        sh '''
            docker build \
              -t abhishekgowdrum/devops-project4:${BUILD_NUMBER} \
              -t abhishekgowdrum/devops-project4:latest .
        '''
    }
}


        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                        echo "\$PASS" | docker login -u "\$USER" --password-stdin
                        docker push ${REGISTRY}:${IMAGE_TAG}
                        docker push ${REGISTRY}:latest
                        docker logout
                    """
                }
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Create EC2') {
            steps {
                dir('Terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Get EC2 IP') {
            steps {
                script {
                    env.EC2_IP = sh(
                        script: 'cd Terraform && terraform output -raw ec2_public_ip',
                        returnStdout: true
                    ).trim()

                    echo "EC2 Public IP: ${env.EC2_IP}"
                }
            }
        }

        stage('Create Ansible Inventory') {
    steps {
        script {
            def ec2IP = sh(
                script: 'cd Terraform && terraform output -raw ec2_public_ip',
                returnStdout: true
            ).trim()

            sh """
                mkdir -p ansible

                cat > ansible/inventory.ini <<EOF
[webserver]
${ec2IP}

[webserver:vars]
ansible_user=ubuntu
ansible_private_key_file=/var/lib/jenkins/.ssh/west2.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOF
            """

            echo "Generated Ansible inventory:"
            sh 'cat ansible/inventory.ini'
        }
    }
}

        stage('Test Ansible Connection') {
    steps {
        sh '''
            echo "Waiting for the new EC2 instance to accept SSH..."

            ansible -i ansible/inventory.ini webserver \
                -m wait_for_connection \
                -a "timeout=300 sleep=10 connect_timeout=5"

            echo "SSH is ready. Testing Ansible..."
            ansible -i ansible/inventory.ini webserver -m ping
        '''
    }
}

        stage('Deploy Application') {
            steps {
                sh '''
                ansible-playbook \
                -i ansible/inventory.ini \
                ansible/playbook.yml
                '''
            }
        }
    }
    }
    
