
---
- name: Deploy application
  hosts: webserver
  become: yes

  tasks:
    - name: Update Ubuntu package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker and Python Docker support
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-docker
        state: present

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Nginx image
      ansible.builtin.command:
        cmd: docker pull abhishekgowdrum/devops-project2:latest

    - name: Remove existing application container if present
      ansible.builtin.command:
        cmd: docker rm -f myapp
      failed_when: false
      changed_when: false

    - name: Run Nginx container
      ansible.builtin.command:
        cmd: docker run -d --name myapp --restart always -p 80:8080 abhishekgowdrum/devops-project2:latest
